
package pl.szkolenie.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsersRepositoryImplService", targetNamespace = "http://service.szkolenie.pl/", wsdlLocation = "http://localhost:9999/UsersRepository?wsdl")
public class UsersRepositoryImplService
    extends Service
{

    private final static URL USERSREPOSITORYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERSREPOSITORYIMPLSERVICE_EXCEPTION;
    private final static QName USERSREPOSITORYIMPLSERVICE_QNAME = new QName("http://service.szkolenie.pl/", "UsersRepositoryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/UsersRepository?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSREPOSITORYIMPLSERVICE_WSDL_LOCATION = url;
        USERSREPOSITORYIMPLSERVICE_EXCEPTION = e;
    }

    public UsersRepositoryImplService() {
        super(__getWsdlLocation(), USERSREPOSITORYIMPLSERVICE_QNAME);
    }

    public UsersRepositoryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSREPOSITORYIMPLSERVICE_QNAME, features);
    }

    public UsersRepositoryImplService(URL wsdlLocation) {
        super(wsdlLocation, USERSREPOSITORYIMPLSERVICE_QNAME);
    }

    public UsersRepositoryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSREPOSITORYIMPLSERVICE_QNAME, features);
    }

    public UsersRepositoryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsersRepositoryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsersRepositoryImpl
     */
    @WebEndpoint(name = "UsersRepositoryImplPort")
    public UsersRepositoryImpl getUsersRepositoryImplPort() {
        return super.getPort(new QName("http://service.szkolenie.pl/", "UsersRepositoryImplPort"), UsersRepositoryImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsersRepositoryImpl
     */
    @WebEndpoint(name = "UsersRepositoryImplPort")
    public UsersRepositoryImpl getUsersRepositoryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.szkolenie.pl/", "UsersRepositoryImplPort"), UsersRepositoryImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSREPOSITORYIMPLSERVICE_EXCEPTION!= null) {
            throw USERSREPOSITORYIMPLSERVICE_EXCEPTION;
        }
        return USERSREPOSITORYIMPLSERVICE_WSDL_LOCATION;
    }

}
