
package pl.szkolenie.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserRepositoryImpl", targetNamespace = "http://service.szkolenie.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserRepositoryImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://service.szkolenie.pl/", className = "pl.szkolenie.ws.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://service.szkolenie.pl/", className = "pl.szkolenie.ws.AddUserResponse")
    public long addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns pl.szkolenie.ws.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.szkolenie.pl/", className = "pl.szkolenie.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.szkolenie.pl/", className = "pl.szkolenie.ws.GetUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<pl.szkolenie.ws.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.szkolenie.pl/", className = "pl.szkolenie.ws.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.szkolenie.pl/", className = "pl.szkolenie.ws.GetAllResponse")
    public List<User> getAll();

}
