
package pl.szkolenie.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserRepositoryImplService", targetNamespace = "http://service.szkolenie.pl/", wsdlLocation = "http://localhost:9999/UsersRepository?wsdl")
public class UserRepositoryImplService
    extends Service
{

    private final static URL USERREPOSITORYIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(pl.szkolenie.ws.UserRepositoryImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = pl.szkolenie.ws.UserRepositoryImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9999/UsersRepository?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/UsersRepository?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERREPOSITORYIMPLSERVICE_WSDL_LOCATION = url;
    }

    public UserRepositoryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserRepositoryImplService() {
        super(USERREPOSITORYIMPLSERVICE_WSDL_LOCATION, new QName("http://service.szkolenie.pl/", "UserRepositoryImplService"));
    }

    /**
     * 
     * @return
     *     returns UserRepositoryImpl
     */
    @WebEndpoint(name = "UserRepositoryImplPort")
    public UserRepositoryImpl getUserRepositoryImplPort() {
        return super.getPort(new QName("http://service.szkolenie.pl/", "UserRepositoryImplPort"), UserRepositoryImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserRepositoryImpl
     */
    @WebEndpoint(name = "UserRepositoryImplPort")
    public UserRepositoryImpl getUserRepositoryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.szkolenie.pl/", "UserRepositoryImplPort"), UserRepositoryImpl.class, features);
    }

}
